<div class="container-fluid">
    <div class="container">
        <h1>Connexion</h1>
        <form action="" method="post">
            <div class="form-group">
                <label for="name">Pseudo</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="name">
            </div>
            <div class="form-group">
                <label for="password">Mot de passe</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe">
            </div>
            <button type="submit" class="btn btn-primary" name="login">Se connecter</button>
        </form>
    </div>
</div>
    